### ISSUE TITLE
Improve installation steps in readme

### ISSUE THREAD

**Issue by cdhiraj40** [cdhiraj40/LeetDroid#16]
**Is your feature request related to a problem? Please describe.**
The current [installation steps](https://github.com/cdhiraj40/LeetDroid/blob/development/app/src/main/java/com/cdhiraj40/leetdroid/ui/fragments/ExploreProblemsFragment.kt) in readme are not very beginner friendly and does not have command written for all steps.

**Describe the solution you'd like**
We should have screenshots of steps like forking this project and commands for cloning the project too. Along with that, some commands require a link to it like creating a PR can have a link directly to open the PR page.

**Comment by imgourav** [comment]
Assign this issue to me, I can improve the installation steps!
