### ISSUE TITLE
Fix typos and improve  README.md

### ISSUE THREAD

**Issue by slim-codes** [cdhiraj40/LeetDroid#18]
**Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- There are a few minor grammatical improvements that can be made to the README

**Describe the solution you'd like**

* Improve the grammatical structure of README.md
* Fix typos/spelling errors

**Comment by cdhiraj40** [comment]
You can create a PR of your changes and depending on the size of the changes I will decide whether to merge or not!

**Comment by slim-codes** [comment]
> You can create a PR of your changes and depending on the size of the changes I will decide whether to merge or not!

Alright then, I shall create a PR soon
