### ISSUE TITLE
handling internet connection

### ISSUE THREAD

**Issue by cdhiraj40** [cdhiraj40/LeetDroid#5]
**Is your feature request related to a problem? Please describe.**
Currently, a user needs an active internet connection for using an app. There should be proper checks for internet connection.  

**Describe the solution you'd like**
Checking if there is an active connection is more than enough. It might be a big change as it has not been implemented yet and this change has to be done throughout the app. A proper solution I can think of is implementing this to one-one screens and making PR for it.  

**Describe alternatives you've considered**
None

**Comment by BismeetSingh** [comment]
I would like to do this.

**Comment by BismeetSingh** [comment]
Hi, can you assign this to me
