### ISSUE TITLE
Some of the content in question is missing

### ISSUE THREAD

**Issue by naqushab** [cdhiraj40/LeetDroid#6]
![Screenshot_20220317-191943](https://user-images.githubusercontent.com/6817118/158823580-5becb03b-73b8-41cd-bb43-ac84cf23323e.jpg)

This is daily leetcode challenge page - as you can see the list is missing that denotes the problem rules.

**Comment by cdhiraj40** [comment]
Hey @naqushab I can see this happening too, I will try to resolve it soon.

**Comment by SanjaySargam** [comment]
Can u plz assign me. I want to contribute
