### ISSUE TITLE
Adding progressbar on contributors list screen

### ISSUE THREAD

**Issue by cdhiraj40** [cdhiraj40/LeetDroid#7]
**Is your feature request related to a problem? Please describe.**
Currently, there is no progress bar for the contributor list screen, which makes the experience bad for the user. It would be great to have a progress bar there. **Make sure that you are using the same progress bar(loading view) on the screen which is used for most of the screens.**

**Describe the solution you'd like**
This one should be an easy issue to solve, all you have to do is just check out the implementation of the progress bar on different screens. You can find it here for [question screen](https://github.com/cdhiraj40/LeetDroid/blob/development/app/src/main/java/com/cdhiraj40/leetdroid/ui/fragments/question/QuestionFragment.kt)

Steps:
1. Show the loading view at the start of the screen
2. Hide it once the contributor list has been fetched 

**Describe alternatives you've considered**
None

**Additional context**
You can ping me in the comments if additional information is needed!

**Comment by SanjaySargam** [comment]
Can you plz assign me?

**Comment by SanjaySargam** [comment]
Could you tell me exactly which activity?

**Comment by cdhiraj40** [comment]
> Could you tell me exactly which activity?

yes sure! You can find the code for contributors list here: https://github.com/cdhiraj40/LeetDroid/blob/development/app/src/main/java/com/cdhiraj40/leetdroid/ui/fragments/preferences/ContributorsFragment.kt

**Comment by SanjaySargam** [comment]
> > Could you tell me exactly which activity?
> 
> yes sure! You can find the code for contributors list here: https://github.com/cdhiraj40/LeetDroid/blob/development/app/src/main/java/com/cdhiraj40/leetdroid/ui/fragments/preferences/ContributorsFragment.kt
> 
> @SanjaySargam would you like to work on this?

Yess

**Comment by SanjaySargam** [comment]
@cdhiraj40 where the ContributorsFragment Activity used in the app?
I can't able to find

**Comment by SanjaySargam** [comment]
> > @cdhiraj40 where is the ContributorsFragment Activity used in the app?
> > I can't able to find
> 
> You can `ctrl + click` on the class name and it will show you where it is getting used.

Yah I know. I find the files. But didn't find where exactly this activity used in app

**Comment by SanjaySargam** [comment]
> > > > @cdhiraj40 where is the ContributorsFragment Activity used in the app?
> > > > I can't able to find
> > > 
> > > You can `ctrl + click` on the class name and it will show you where it is getting used.
> > 
> > Yah I know. I find the files. But didn't find where exactly this activity used in app
> 
> Left Menu -> About -> Contributors

Yahh finally got it. 😅😅

**Comment by SanjaySargam** [comment]
is there any need to add error_loading_view?

**Comment by cdhiraj40** [comment]
> is there any need to add error_loading_view?

yes add it, just like other screens if something goes wrong while fetching the contributors

**Comment by SanjaySargam** [comment]
> > is there any need to add error_loading_view?
> 
> yes add it, just like other screens if something goes wrong while fetching the contributors

Okk cool
