### ISSUE TITLE
Added loading view for the recent submissions

### ISSUE THREAD

**Issue by cdhiraj40** [cdhiraj40/LeetDroid#9]
**Is your feature request related to a problem? Please describe.**
Currently, there is a pretty common progress bar for the recent submissions screen while most of the screens use a better-looking progress bar. It would be great to have the same progress bar there. Make sure that you are using the same progress bar(loading view) on the screen which is used for most of the screens.

**Describe the solution you'd like**
This one should be an easy issue to solve, all you have to do is first remove the older progress bar and replace it with the other one. You can check out the implementation of the progress bar on different screens which you can find it here for [question screen](https://github.com/cdhiraj40/LeetDroid/blob/development/app/src/main/java/com/cdhiraj40/leetdroid/ui/fragments/question/QuestionFragment.kt)

Steps:

1. Show the loading view at the start of the screen
2. Hide it once the contributor list has been fetched

**Describe alternatives you've considered**
None

**Additional context**
You can ping me in the comments if additional information is needed!

**Comment by BismeetSingh** [comment]
Hi, I would like to work on this.

**Comment by cdhiraj40** [comment]
sure @BismeetSingh go ahead!! Let me know if you need help!

**Comment by BismeetSingh** [comment]
https://user-images.githubusercontent.com/13601266/193454742-1399e5e7-65f8-4b3e-8625-c474dfb36364.mp4
